export const GET_NBA_CRITIC = 'GET_NBA_CRITIC'
export const GET_NHL_CRITIC ='GET_NHL_CRITIC'
export const GET_PGA_CRITIC ='GET_PGA_CRITIC'

export const GET_NBA_FANS = 'GET_NBA_FANS'
export const GET_NHL_FANS ='GET_NHL_FANS'
export const GET_PGA_FANS ='GET_PGA_FANS'

export const GET_NBA_ALLTIME = 'GET_NBA_ALLTIME'
export const GET_NHL_ALLTIME ='GET_NHL_ALLTIME'
export const GET_PGA_ALLTIME ='GET_PGA_ALLTIME'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const POST_SPORT_LIST = 'POST_SPORT_LIST'



