export const GET_NBA_CRITIC = 'GET_NBA_CRITIC'
export const GET_NHL_CRITIC ='GET_NHL_CRITIC'
export const GET_PGA_CRITIC ='GET_PGA_CRITIC'

export const GET_NBA_FANS = 'GET_NBA_FANS'
export const GET_NHL_FANS ='GET_NHL_FANS'
export const GET_PGA_FANS ='GET_PGA_FANS'
export const DELETE_FANS = 'DELETE_FANS'

export const GET_NBA_PLAYER = 'GET_NBA_PLAYER'
export const GET_NHL_PLAYER ='GET_NHL_PLAYER'
export const GET_PGA_PLAYER ='GET_PGA_PLAYER'

export const GET_NBAFANS_ALLTIME = 'GET_NBAFANS_ALLTIME'
export const GET_NHLFANS_ALLTIME ='GET_NHLFANS_ALLTIME'
export const GET_PGAFANS_ALLTIME ='GET_PGAFANS_ALLTIME'

export const GET_NBAPLAYERS_ALLTIME = 'GET_NBAPLAYERS_ALLTIME'
export const GET_NHLPLAYERS_ALLTIME ='GET_NHLPLAYERS_ALLTIME'
export const GET_PGAPLAYERS_ALLTIME ='GET_PGAPLAYERS_ALLTIME'

export const GET_NBA_ALLTIME = 'GET_NBA_ALLTIME'
export const GET_NHL_ALLTIME ='GET_NHL_ALLTIME'
export const GET_PGA_ALLTIME ='GET_PGA_ALLTIME'

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER'
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const POST_SPORT_LIST = 'POST_SPORT_LIST'



